# Generated by Django 3.0.2 on 2020-01-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='revolution.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('votes', models.IntegerField()),
                ('comments', models.ManyToManyField(to='revolution.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='revolution.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revolution.Entry')),
            ],
            bases=('revolution.entry',),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revolution.Entry')),
                ('improvements', models.ManyToManyField(related_name='_solution_improvements_+', to='revolution.Solution')),
                ('source_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revolution.Problem')),
            ],
            bases=('revolution.entry',),
        ),
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(to='revolution.Solution'),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revolution.Entry')),
                ('improvements', models.ManyToManyField(related_name='_initiative_improvements_+', to='revolution.Initiative')),
            ],
            bases=('revolution.entry',),
        ),
    ]
