# Generated by Django 3.0.2 on 2020-01-11 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='revolution.Comment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='improvements',
            field=models.ManyToManyField(blank=True, default=None, related_name='_initiative_improvements_+', to='revolution.Initiative'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(blank=True, default=None, to='revolution.Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='improvements',
            field=models.ManyToManyField(blank=True, default=None, related_name='_solution_improvements_+', to='revolution.Solution'),
        ),
    ]
