# Generated by Django 3.0.2 on 2020-01-12 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0003_auto_20200112_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='improvement_of',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revolution.Solution'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 1, 24, 51, 748347)),
        ),
    ]
