# Generated by Django 3.0.2 on 2020-01-12 02:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0004_auto_20200112_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 3, 35, 22, 808583)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='revolution.Tag'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='improvement_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revolution.Solution'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
