# Generated by Django 3.0.2 on 2020-01-12 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0005_auto_20200112_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='improvement_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revolution.Initiative'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 4, 0, 38, 270234)),
        ),
    ]
