# Generated by Django 3.0.2 on 2020-01-12 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolution', '0007_auto_20200112_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='subinitiatives',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 4, 46, 21, 99985)),
        ),
    ]
